@url = http://127.0.0.1:8080/

###
// Delete_Req1
DELETE {{url}}app?id_employee=ce44e4b7-a464-4088-88b3-1b8883a11f8d
// Mitarbeiter löschen

###
// Delete_Req2
DELETE {{url}}app?id_training=a87a368e-3132-41dd-b4b3-35a808f98493
// Training löschen

###
// Delete_Req3
DELETE {{url}}app?id_training=c738556c-f523-498d-95e2-dfbc5b195786&index_qualification=1
// Qualifikation mit Index 1 von einer Weiterbildung löschen