@url = http://127.0.0.1:8080/

GET {{url}}

###

DELETE {{url}}app/14/False/True
// Mitarbeiter löschen
###

DELETE {{url}}app/9/True/False
// Training löschen

GET {{url}}app/None/False/True

###

GET {{url}}app/None/False/False