@url = http://127.0.0.1:8080/

###
// Delete_Req1
DELETE {{url}}app?id_employee=4
// Mitarbeiter löschen

###
// Delete_Req2
DELETE {{url}}app?id_training=8
// Training löschen

###
// Delete_Req3
DELETE {{url}}app?id_training=6&index_qualification=1
// Qualifikation mit Index 1 von der Weiterbildung 6 löschen